# Generated by Django 5.1 on 2025-01-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='ledger',
            field=models.IntegerField(default=0),
        ),
    ]
