# Generated by Django 5.1 on 2025-01-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientdata_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='ledger',
            field=models.IntegerField(null=True),
        ),
    ]
