# Generated by Django 5.1 on 2024-12-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cash_in_date_cash_out_date_sales_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash_in',
            options={'verbose_name_plural': 'Cash In'},
        ),
        migrations.AlterModelOptions(
            name='cash_out',
            options={'verbose_name_plural': 'Cash Out'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
